### ISSUE TITLE
Create a user account on design.1337lawyers.com

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#107]
To get an idea of how authentication works, please create an account on design.1337lawyers.com with your emails. You should notice that if you do not use your personal email addresses, you are forbidden from creating an account

When you are done, [the Authenticated Route doc](https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=AuthenticatedRoute&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) should allow you to click the "Private Link" and [the current user consumer page](https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=CurrentUserConsumer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) should show your name and unique ID.

Please create an account and add any relevant documentation to the repo.

**Comment by shicholas** [comment]
To create an account, you will need to first [Signup](https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=Signup&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), then you should receive a code in your email. Use that code [on this page](https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=ConfirmAccount&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to confirm your account. You should then be able to [Login](https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=Login&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

**Comment by quantumjockey** [comment]
@shicholas It worked! my email and app GUID show in the footer of the Current User Consumer page.

**Comment by shicholas** [comment]
cool thanks

**Comment by bphallad** [comment]
I'll check it out tonight.

**Comment by shicholas** [comment]
sweet thanks, less is more. haha there's no reason we shouldn't be able to
share all of this work.

**Comment by shicholas** [comment]
closing this since you both created an account, thanks.
