### ISSUE TITLE
Text Area Component

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#22]

**Comment by quantumjockey** [comment]
Hey Nick! I'm gonna work on this and study React + TypeScript tonight. I can't move the card to "In Progress" though. Can you?

**Comment by quantumjockey** [comment]
Además, esto es lo que quiero decir cuando dije "Skeleton" para los componentes:

https://medium.com/gronda/the-illusion-of-speed-loading-states-with-react-1c676ccce484

Pienso que es muy genial, pero necesito para averiguar cómo usarlo.  XD

**Comment by shicholas** [comment]
I think this is premature optimization. We can build this as a HOC later on. Please build the form components sans skeletons.
