### ISSUE TITLE
Menu component updates

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#29]
On mobile, clicking a link should close the menu, like the `Navbar` component.

**Comment by shicholas** [comment]
When you click a link in the navigation, the entire window closes

**Comment by shicholas** [comment]
Also, on mobile devices, the `Menu` component has distroted styles:

![Screen Shot 2018-11-25 at 15.10.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a80b9242d1e1b0011083a1f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456f66b7191a379ea0c2a51415d4bbe5d4a1f06a3a3dc78e2a436628f0e0ceed83f5d75c73443f9ecd11fbf00e824da4dd0b3e99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5bf743e64951a5153562f43b.png)

This should look like the Navbar on mobile devices, or https://design.1337lawyers.com/?selectedKind=Navigation&selectedStory=Navbar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by bphallad** [comment]
@shicholas So you want the alignment fixed so menu and navbar match, right?

**Comment by shicholas** [comment]
Yes please, thank you.
