### ISSUE TITLE
Update Markdown Prism Component

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#31]
For syntax highlighting

**Comment by shicholas** [comment]
hey @bphallad, when you have time I think this is a better one to start with. it's way less overhead of things to think about

**Comment by bphallad** [comment]
I see highlight.js in package.json already. Not sure if you want certain themes or what the goal is here.

**Comment by shicholas** [comment]
did you have a comment here?

Check out design.1337lawyers.com, like https://design.1337lawyers.com/?selectedKind=Forms&selectedStory=Setup&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel. On GitHub, when you write in GitHub flavored markdown, it recognizes and apply is syntax highlighting.

**Comment by shicholas** [comment]
TIL Highlight is deprecated, https://prismjs.com/#languages-list is what's recommended

**Comment by shicholas** [comment]
assigning myself this one. I'll finish it
