### ISSUE TITLE
A test to ensure all stories are properly loading

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#72]

**Comment by shicholas** [comment]
Something like a feature test that checks if the story renders without an error

**Comment by shicholas** [comment]
E.g. a test here; https://design.1337lawyers.com/?selectedKind=Authentication&selectedStory=ChangePassword&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel should fail because the story is not properly rendering

**Comment by shicholas** [comment]
As we talked about, please test the story components themselves the same way we have been testing our other components with enzyme.

e.g. in the file `navigation/stories.tsx` this code:

```tsx
storiesOf('Navigation', module)
  .addDecorator(StoryRouter())
  .add('Menu', () => <MenuStory />)
  .add('Navbar', () => <NavbarStory />)
  .add('Breadcrumbs', () => (
    <Section>
      <Container>
        An example of the breadcrumb component exists in the Menu tab.
      </Container>
    </Section>
  ));
```

Please write a test for `MenuStory` and `NavbarStory`

**Comment by quantumjockey** [comment]
I tried to correct the remaining tests after removing the authentication tests before pushing. Everything fails upon importing the markdown content. I don't know if that's due to it not compiling the markdown until after the TSX/JSX is processed. Doing a little more research to find out. Will start working on that l33t form straight afterward.

**Comment by quantumjockey** [comment]
Rectified the markdown imports when running Jest (via the [markdown-loader-jest](https://www.npmjs.com/package/markdown-loader-jest) plugin). The contact form story test still fails for an unexpected identifier. Will look into it after I add the form to l33t web.

**Comment by shicholas** [comment]
updated & reflected on master.
