### ISSUE TITLE
Update Contact Form with Checkbox and Number Input

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#77]
Check out the contact form: https://design.1337lawyers.com/?selectedKind=Forms&selectedStory=Example%3A%20Contact%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Can you please add your newly created `Checkbox` and `NumberInput` forms here?

I just pushed https://github.com/1337lawyers/design/commit/1ac0f62100c9167dda4ab170b776eda563a3f0f5 which gives you two fields to submit the form from.

**Comment by bphallad** [comment]
Sure.
