### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#79]
https://react-select.com/

Please add this like you have the number input & checkbox

**Comment by shicholas** [comment]
Select should have these styles: https://bulma.io/documentation/form/select/

**Comment by bphallad** [comment]
@shicholas how do I turn on bulma css in storybook?

**Comment by shicholas** [comment]
I'm not sure, I import the main stylesheet in `welcome/stories.tsx`, so all you should need to do is use the appropriate class names. 

I wouldn't spend that much time on CSS Styles as I'd like to convert this repo to `react-native-web` soon.

**Comment by bphallad** [comment]
ok, I pass in the class name which can be bulma stylings that should work

**Comment by bphallad** [comment]
Should I pass in styles with chroma-js as in the examples for react-select?

https://codesandbox.io/s/wyyp23okl7?module=/example.js

**Comment by shicholas** [comment]
Sure, if it's easy. The class names will be what you said, ones from Bulma.

This style in the codepen is similar to how react native styles work too so
it puts on the right track.

**Comment by shicholas** [comment]
last thing here @bphallad.

Please visit https://design.1337lawyers.com/?selectedKind=Forms&selectedStory=Example%3A%20Contact%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel and fill out the form.

You should receive an email at the email address you entered in from `development@1337lawyers.com`. I will be notified as well when that email gets sent.

Then from there, please add a new field for a select box. Please check out the `contactForm.gql` file which contains the GraphQL Mutation used by the form when submitting data to the back-end. You should be adding a new field there to represent your select box. 

If done the way I hope, the form after you add the select box should **not** work because the corresponding select field needs to be added to the backend. Once I do my part there, the form should work again.

Hope this makes sense, please ping me with any questions. Thanks!

**Comment by bphallad** [comment]
I tried submitting twice but never received an email.

**Comment by shicholas** [comment]
Sorry about that. I needed to bust the cache. Please try again.

**Comment by bphallad** [comment]
email worked! nice job

**Comment by bphallad** [comment]
@shicholas see my latest feature/select-component branch

I cannot get the submit button to enable while making favoriteColors required by Yup. It doesn't matter if I select colors in the dropdown.

I've tried a few combinations for yup.array() to get a minimum of one selection:
https://github.com/jquense/yup#arrayminlimit-number--ref-message-string-schema

Any suggestions?

If I remove the line, then I can submit the form but I am not getting the email on this branch. So maybe there's an issue with my .gql mutation?

**Comment by shicholas** [comment]
please check out https://github.com/1337lawyers/design/pull/85/files

**Comment by shicholas** [comment]
thanks!
