### ISSUE TITLE
Create a contact form on L33t Web

### ISSUE THREAD

**Issue by shicholas** [1337lawyers/design#93]
First, go to design.1337lawyers.com.
Then click Forms on the right navbar
Then click Ex: Contact Form on the right navbar

Fill out the form, you should receive an email to development@1337lawyers.com

The goal now is to copy and paste this form into https://github.com/1337lawyers/web, a separate repo that uses the design repository so we can add a contact form there.

The form should have three fields:

A string input for `email`
A string input for `subject`
A text area input for `message`

If you need help understanding the current Contact Form in the design repo, please contact me.

Hopefully, by the end, you'll have an understanding of:

* Apollo's Mutation Component
* Formik

**Comment by quantumjockey** [comment]
@shicholas  I think understand how GraphQL works after reading through the Apollo docs, but I can't shake this one compile error,

```
ERROR in [at-loader] ./src/routes/contact/contactForm.tsx:15:31                                                                            │warning "apollo-client > apollo-link@1.2.2" has incorrect peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".                       
    TS2307: Cannot find module './contactForm.gql'. 
```

despite adding graphql-tag and the other deps & configs from the design repo that seem to resolve *.gql files as text. What am I missing?

**Comment by shicholas** [comment]
the typings.d.ts file has information about gql files and importing them as
strings using Typescript Modules. I just added this to master.

Thanks!
